### ISSUE TITLE
Arguments passed on resolve

### ISSUE THREAD

**Issue by david-spaeth** [akane/AnnotationInject#6]
Thank for your job.

I need to register a service with arguments passed on resolve: For example:

```
 container.resolve(Cat.self, arguments: "Steve", 42)
````
If i understood, I must use `// sourcery: provider` with custom factory: 

```
// sourcery: provider
class AppProvider {
    static func instantiate(resolver: Resolver, name: String, age: Int) -> Cat {
        return Cat(name, age: age)
    }
}
```

But resolve returns an optional

Did i forget something ?

Can you generate secure methods like this :

```
 func registeredService(arg1: Stings, arg2: Int) -> Cat {
        return resolve(cat.self, arguments: arg1, arg2)!
    }
```

Or is there another trick ?

Thank's

**Comment by pjechris** [comment]
Hi @david-spaeth!

As of today AnnotationInject is requiring you to state explicitly when you expect a parameter to be passed as an argument:
```swift
// sourcery: provider
class AppProvider {
    static func instantiate(resolver: Resolver, /* sourcery: provided */ name: String, /* sourcery: provided */ age: Int) -> Cat {
        return Cat(name: String, age: Int)
    }
}
```

Also, if you have a declared initializer inside your class you can use it directly instead of making a provider:
```swift
// sourcery: inject
class Cat {
  init(/* sourcery: provided */ name: String, /* sourcery: provided */ age: Int)
}
```

Requiring this annotation is not great, maybe I should consider non resolvable parameters as service arguments. This is an open question!

**Comment by david-spaeth** [comment]
It works like a charm ! 
Can you add some note about this in the readme file ?
Yes this annotation is not sexy.

**Comment by pjechris** [comment]
Done, thank your for your feedback!
